In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv("./processed_data/stance_width_data5.csv")

In [3]:
df['label_1']=df.label_1.str.lower()

In [4]:
df_filt = df.loc[~df.label_1.str.contains("not enough info") ]

In [5]:
df_filt.loc[df_filt.label_1=='narrow','label_1']='01'
df_filt.loc[df_filt.label_1=='slightly narrow','label_1']='02'
df_filt.loc[df_filt.label_1=='ok','label_1']='03'
df_filt.loc[df_filt.label_1=='slightly wide','label_1']='04'
df_filt.loc[df_filt.label_1=='wide','label_1']='05'

/Users/gwattal/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [6]:
df_filt

Unnamed: 0           name  stance_heel  confidence_min_heel  stance_ankle  \
0            1    image22.png     1.088060             0.482316      1.367805   
1           11    image23.png     1.091162             0.368627      1.293202   
2            8       images10     1.162537             0.575121      1.311203   
3            4       images14     1.216810             0.658765      1.405309   
4           59       images15     1.027805             0.556757      1.227870   
5           51       images16     0.954208             0.485099      1.164394   
7           45       images18     1.372329             0.249179      1.545958   
8           22       images19     1.506750             0.541831      1.652482   
9           20       images20     0.999950             0.560490      1.257205   
10          23       images24     0.894968             0.621125      1.092730   
11          44       images25     0.988986             0.523673      1.180211   
13          29       images27     1.134135             0.604726      1.304911   
14          58       images28     0.095583             0.478187      0.252378   
16          27       images34     1.708705             0.720442      1.929439   
17          42        images6     1.182376             0.706502      1.418579   
18          26        images7     1.384942             0.781627      1.565313   
19          50        images8     1.339823             0.575919      1.619577   
21          35  IMG_2267.jpeg     0.952904             0.755419      1.111246   
22          25  IMG_2268.jpeg     0.937829             0.739283      1.171519   
23           9  IMG_2270.jpeg     0.906325             0.688003      1.108942   
24          52  IMG_2272.jpeg     1.337791             0.697874      1.526862   
25          21  IMG_2275.jpeg     0.562411             0.768179      0.719151   
26          31  IMG_2280.jpeg     1.153987             0.668748      1.346850   
27          17  IMG_2288.jpeg     0.960246             0.791725      1.196188   
28          37  IMG_2291.jpeg     1.117245             0.804517      1.389502   
29          54  IMG_2299.jpeg     0.891812             0.769523      0.998908   
30          55  IMG_2304.jpeg     1.542255             0.728152      1.605737   
31          57  IMG_2307.jpeg     0.416765             0.807906      0.519864   
32           0  IMG_2316.jpeg     0.666653             0.818403      0.777341   
33          18  IMG_2318.jpeg     1.195191             0.763475      1.345940   
34          30  IMG_2320.jpeg     1.607485             0.834501      1.715565   
35          47  IMG_2322.jpeg     0.203152             0.813802      0.369577   
36          28   IMG_3001.png     0.917613             0.660212      1.123399   
37           2   IMG_3002.png     1.336526             0.690680      1.526040   
38          13   IMG_3003.png     1.168984             0.641752      1.376481   
39          32   IMG_3004.png     1.389198             0.780031      1.591779   
40          24   IMG_3005.png     1.307753             0.809898      1.519510   
41          16   IMG_3006.png     0.854688             0.816811      1.104904   
42           6   IMG_3007.png     0.312059             0.856101      0.499763   
43          39   IMG_3008.png     1.643471             0.749486      1.864391   
44          46   IMG_3009.png     1.485164             0.557777      1.653590   
45          40   IMG_3010.png     0.404195             0.589073      0.384293   
46          33   IMG_3011.png     1.320328             0.547423      1.475806   
47          56   IMG_3012.png     0.722130             0.654070      0.891617   
48          49   IMG_3013.png     0.710998             0.599665      0.876420   
49          36   IMG_3014.png     0.717759             0.504674      0.872670   
50          43   IMG_3015.png     0.743452             0.738193      0.952162   
51          53   IMG_3016.png     0.809480             0.748248      1.000211   
52          38       index_11     0

In [35]:
df_filt3=df_filt.drop([0,1,35,44,45,46,48,49,50,51]).query('confidence_min_wgt_avg > 0.7')

In [36]:
name=df_filt3.name.values

In [37]:
path="/Users/gwattal/squatsmart/output_keypoints/"

In [38]:
features=[]
for file in name:
    #print(file)
    xi,yi,c=np.loadtxt(path + file+"_keypoints.txt").T
    features.append(np.hstack((xi,yi))/max(np.hstack((xi,yi))))

In [39]:
X=np.asarray(features)
Y=df_filt3.label_1.values
Y=Y.astype(int)

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.33, random_state=42)

In [41]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(max_depth=5) 
tree_clf.fit(X_train, y_train)
y_pred=tree_clf.predict(X_test)
tree_clf.score(X_test,y_test)

0.5

In [42]:
y_pred

array([4, 1, 1, 3, 1, 5, 5, 3, 3, 5])

In [43]:
y_test

array([3, 4, 3, 5, 1, 5, 5, 3, 2, 5])

In [44]:
feat_imp=tree_clf.feature_importances_

In [45]:
feat_imp

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.12273902, 0.19147287, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.22592593, 0.11046512, 0.        , 0.        , 0.25366064,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.09573643, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [34]:
X_train.shape

(30, 50)