In [30]:
import json
import os
import numpy as np

In [4]:
os.listdir()

['MOV_0003_frame58_keypoints.json',
 'MOV_0003_frame249_keypoints.json',
 'MOV_0003_frame199_keypoints.json',
 'MOV_0002_frame23_keypoints.json',
 'MOV_0002_frame36_keypoints.json',
 'MOV_0003_frame117_keypoints.json',
 'MOV_0003_frame102_keypoints.json',
 'MOV_0003_frame29_keypoints.json',
 'MOV_0003_frame238_keypoints.json',
 'MOV_0002_frame47_keypoints.json',
 'MOV_0002_frame52_keypoints.json',
 'MOV_0003_frame173_keypoints.json',
 'MOV_0003_frame166_keypoints.json',
 'MOV_0003_frame6_keypoints.json',
 'MOV_0001_frame8_keypoints.json',
 'MOV_0001_frame46_keypoints.json',
 'MOV_0001_frame53_keypoints.json',
 'MOV_0003_frame230_keypoints.json',
 'MOV_0003_frame225_keypoints.json',
 'MOV_0003_frame34_keypoints.json',
 'MOV_0003_frame21_keypoints.json',
 'MOV_0001_frame22_keypoints.json',
 'MOV_0001_frame37_keypoints.json',
 'MOV_0003_frame184_keypoints.json',
 'MOV_0003_frame191_keypoints.json',
 'MOV_0003_frame254_keypoints.json',
 'MOV_0003_frame241_keypoints.json',
 'MOV_0003_frame5

In [45]:
json_files = [pos_json for pos_json in os.listdir() if pos_json.endswith('.json')]


for json_file json_files:
    with open(json_file) as f:
        print(json_file)
        data = json.load(f)
        keypoints_list=data['people'][0]['pose_keypoints_2d']
        keypoints_array=np.asarray(keypoints_list).reshape(25,3)
        np.savetxt("../text-file/"+json_file.replace(".json",'.txt'),keypoints_array,delimiter=' ')
        print("done with",json_file)
print("done")

SyntaxError: invalid syntax (<ipython-input-45-67e21a5abea0>, line 1)

In [9]:
json_file='MOV_0003_frame58_keypoints.json'

In [38]:
with open(json_file) as f:
        data = json.load(f)
        keypoints_list=data['people'][0]['pose_keypoints_2d']
        keypoints_array=np.asarray(keypoints_list).reshape(25,3)
        np.savetxt("../text-file/"+json_file.replace(".json",'.txt'),keypoints_array,delimiter='')

In [16]:
x=data['people']

In [26]:
x[0]['pose_keypoints_2d']

[524.501,
 744.283,
 0.92014,
 540.069,
 890.979,
 0.909398,
 409.052,
 896.301,
 0.870397,
 293.759,
 979.842,
 0.90458,
 152.366,
 906.788,
 0.927674,
 681.282,
 885.573,
 0.83714,
 817.507,
 969.521,
 0.901391,
 938.077,
 869.872,
 0.902768,
 555.568,
 1142.5,
 0.804251,
 466.701,
 1147.46,
 0.770545,
 408.981,
 1367.48,
 0.863444,
 477.102,
 1561.41,
 0.906963,
 644.819,
 1142.41,
 0.77473,
 702.522,
 1362.33,
 0.876384,
 665.718,
 1561.49,
 0.87501,
 492.894,
 718.171,
 0.923415,
 555.773,
 712.96,
 0.923901,
 451.136,
 739.074,
 0.889207,
 597.722,
 728.396,
 0.857516,
 691.911,
 1645.33,
 0.874921,
 723.289,
 1629.52,
 0.863514,
 639.547,
 1566.65,
 0.715199,
 435.335,
 1640,
 0.861681,
 414.292,
 1624.12,
 0.850223,
 508.593,
 1566.49,
 0.884703]

In [34]:
json_file.replace(".json",'.txt')

'MOV_0003_frame58_keypoints.txt'

In [41]:
json_file='MOV_0001_frame37_keypoints.json'
with open(json_file) as f:
        data = json.load(f)
        keypoints_list=data['people'][0]['pose_keypoints_2d']
        keypoints_array=np.asarray(keypoints_list).reshape(25,3)
        print(keypoints_array)

[[4.92717e+02 8.54078e+02 9.25988e-01]
 [4.92972e+02 9.43281e+02 9.33288e-01]
 [3.77735e+02 9.38206e+02 8.86359e-01]
 [2.57108e+02 9.90535e+02 9.03585e-01]
 [1.31444e+02 9.43474e+02 9.33303e-01]
 [6.08265e+02 9.43469e+02 8.88969e-01]
 [7.44365e+02 9.79875e+02 8.75594e-01]
 [8.70070e+02 9.37927e+02 8.87888e-01]
 [4.87840e+02 1.21036e+03 8.39749e-01]
 [4.24611e+02 1.21032e+03 7.87489e-01]
 [4.03708e+02 1.44628e+03 9.04814e-01]
 [4.45621e+02 1.57730e+03 9.23127e-01]
 [5.66058e+02 1.21048e+03 8.24909e-01]
 [5.87131e+02 1.42531e+03 8.71403e-01]
 [5.76844e+02 1.58226e+03 8.96226e-01]
 [4.71772e+02 8.23028e+02 9.32100e-01]
 [5.18904e+02 8.22916e+02 9.61769e-01]
 [4.35240e+02 8.33200e+02 9.24237e-01]
 [5.50608e+02 8.28218e+02 9.23854e-01]
 [5.92326e+02 1.66089e+03 9.51373e-01]
 [6.18630e+02 1.65032e+03 9.48787e-01]
 [5.66271e+02 1.59270e+03 7.74364e-01]
 [4.30047e+02 1.65580e+03 9.05143e-01]
 [4.03671e+02 1.64529e+03 9.20810e-01]
 [4.66547e+02 1.58239e+03 8.28844e-01]]


In [47]:
json_files = [pos_json for pos_json in os.listdir() if pos_json.endswith('.json')]

In [48]:
json_files

['MOV_0003_frame58_keypoints.json',
 'MOV_0003_frame249_keypoints.json',
 'MOV_0003_frame199_keypoints.json',
 'MOV_0002_frame23_keypoints.json',
 'MOV_0002_frame36_keypoints.json',
 'MOV_0003_frame117_keypoints.json',
 'MOV_0003_frame102_keypoints.json',
 'MOV_0003_frame29_keypoints.json',
 'MOV_0003_frame238_keypoints.json',
 'MOV_0002_frame47_keypoints.json',
 'MOV_0002_frame52_keypoints.json',
 'MOV_0003_frame173_keypoints.json',
 'MOV_0003_frame166_keypoints.json',
 'MOV_0003_frame6_keypoints.json',
 'MOV_0001_frame8_keypoints.json',
 'MOV_0001_frame46_keypoints.json',
 'MOV_0001_frame53_keypoints.json',
 'MOV_0003_frame230_keypoints.json',
 'MOV_0003_frame225_keypoints.json',
 'MOV_0003_frame34_keypoints.json',
 'MOV_0003_frame21_keypoints.json',
 'MOV_0001_frame22_keypoints.json',
 'MOV_0001_frame37_keypoints.json',
 'MOV_0003_frame184_keypoints.json',
 'MOV_0003_frame191_keypoints.json',
 'MOV_0003_frame254_keypoints.json',
 'MOV_0003_frame241_keypoints.json',
 'MOV_0003_frame5