In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import os

In [2]:
text_files = [pos_text for pos_text in os.listdir('../text-file/') if pos_text.endswith('.txt')]

In [3]:
text_files

['MOV_0003_frame228_keypoints.txt',
 'MOV_0001_frame12_keypoints.txt',
 'MOV_0013_frame56_keypoints.txt',
 'MOV_0018_frame74_keypoints.txt',
 'MOV_0003_frame199_keypoints.txt',
 'MOV_0014_frame57_keypoints.txt',
 'MOV_0003_frame295_keypoints.txt',
 'MOV_0005_frame78_keypoints.txt',
 'MOV_0003_frame124_keypoints.txt',
 'MOV_0017_frame7_keypoints.txt',
 'MOV_0007_frame18_keypoints.txt',
 'MOV_0007_frame179_keypoints.txt',
 'MOV_0007_frame398_keypoints.txt',
 'MOV_0012_frame3_keypoints.txt',
 'MOV_0016_frame37_keypoints.txt',
 'MOV_0007_frame650_keypoints.txt',
 'MOV_0007_frame700_keypoints.txt',
 'MOV_0003_frame72_keypoints.txt',
 'MOV_0007_frame325_keypoints.txt',
 'MOV_0007_frame275_keypoints.txt',
 'MOV_0020_frame10_keypoints.txt',
 'MOV_0007_frame647_keypoints.txt',
 'MOV_0007_frame717_keypoints.txt',
 'MOV_0019_frame68_keypoints.txt',
 'MOV_0007_frame332_keypoints.txt',
 'MOV_0007_frame262_keypoints.txt',
 'MOV_0003_frame65_keypoints.txt',
 'MOV_0016_frame20_keypoints.txt',
 'MOV_00

In [4]:
features=[]
path='/Users/gwattal/squatsmart/text-file/'
for text_file in text_files:
    print(text_file)
    xi,yi,c=np.loadtxt(path + text_file).T
    features.append(np.hstack((xi,yi))/max(np.hstack((xi,yi))))

MOV_0003_frame228_keypoints.txt
MOV_0001_frame12_keypoints.txt
MOV_0013_frame56_keypoints.txt
MOV_0018_frame74_keypoints.txt
MOV_0003_frame199_keypoints.txt
MOV_0014_frame57_keypoints.txt
MOV_0003_frame295_keypoints.txt
MOV_0005_frame78_keypoints.txt
MOV_0003_frame124_keypoints.txt
MOV_0017_frame7_keypoints.txt
MOV_0007_frame18_keypoints.txt
MOV_0007_frame179_keypoints.txt
MOV_0007_frame398_keypoints.txt
MOV_0012_frame3_keypoints.txt
MOV_0016_frame37_keypoints.txt
MOV_0007_frame650_keypoints.txt
MOV_0007_frame700_keypoints.txt
MOV_0003_frame72_keypoints.txt
MOV_0007_frame325_keypoints.txt
MOV_0007_frame275_keypoints.txt
MOV_0020_frame10_keypoints.txt
MOV_0007_frame647_keypoints.txt
MOV_0007_frame717_keypoints.txt
MOV_0019_frame68_keypoints.txt
MOV_0007_frame332_keypoints.txt
MOV_0007_frame262_keypoints.txt
MOV_0003_frame65_keypoints.txt
MOV_0016_frame20_keypoints.txt
MOV_0014_frame40_keypoints.txt
MOV_0003_frame282_keypoints.txt
MOV_0003_frame133_keypoints.txt
MOV_0009_frame5_keypoints

MOV_0019_frame41_keypoints.txt
MOV_0007_frame432_keypoints.txt
MOV_0007_frame562_keypoints.txt
MOV_0007_frame147_keypoints.txt
MOV_0007_frame26_keypoints.txt
MOV_0020_frame84_keypoints.txt
MOV_0007_frame425_keypoints.txt
MOV_0007_frame575_keypoints.txt
MOV_0007_frame150_keypoints.txt
MOV_0007_frame31_keypoints.txt
MOV_0021_frame9_keypoints.txt
MOV_0007_frame498_keypoints.txt
MOV_0012_frame74_keypoints.txt
MOV_0019_frame56_keypoints.txt
MOV_0007_frame729_keypoints.txt
MOV_0007_frame679_keypoints.txt
MOV_0009_frame72_keypoints.txt
MOV_0003_frame201_keypoints.txt
MOV_0021_frame25_keypoints.txt
MOV_0001_frame113_keypoints.txt
MOV_0001_frame86_keypoints.txt
MOV_0005_frame51_keypoints.txt
MOV_0017_frame15_keypoints.txt
MOV_0003_frame183_keypoints.txt
MOV_0021_frame16_keypoints.txt
MOV_0009_frame8_keypoints.txt
MOV_0003_frame232_keypoints.txt
MOV_0009_frame41_keypoints.txt
MOV_0017_frame26_keypoints.txt
MOV_0005_frame62_keypoints.txt
MOV_0001_frame120_keypoints.txt
MOV_0007_frame382_keypoints

MOV_0003_frame25_keypoints.txt
MOV_0020_frame50_keypoints.txt
MOV_0019_frame28_keypoints.txt
MOV_0007_frame607_keypoints.txt
MOV_0007_frame757_keypoints.txt
MOV_0016_frame3_keypoints.txt
MOV_0005_frame130_keypoints.txt
MOV_0013_frame7_keypoints.txt
MOV_0016_frame60_keypoints.txt
MOV_0003_frame98_keypoints.txt
MOV_0007_frame58_keypoints.txt
MOV_0007_frame139_keypoints.txt
MOV_0019_frame82_keypoints.txt
MOV_0016_frame77_keypoints.txt
MOV_0005_frame127_keypoints.txt
MOV_0007_frame288_keypoints.txt
MOV_0007_frame184_keypoints.txt
MOV_0003_frame32_keypoints.txt
MOV_0007_frame365_keypoints.txt
MOV_0007_frame235_keypoints.txt
MOV_0007_frame610_keypoints.txt
MOV_0007_frame740_keypoints.txt
MOV_0020_frame47_keypoints.txt
MOV_0013_frame16_keypoints.txt
MOV_0001_frame52_keypoints.txt
MOV_0003_frame268_keypoints.txt
MOV_0005_frame85_keypoints.txt
MOV_0018_frame34_keypoints.txt
MOV_0014_frame17_keypoints.txt
MOV_0005_frame38_keypoints.txt
MOV_0003_frame164_keypoints.txt
MOV_0003_frame311_keypoints.

MOV_0003_frame222_keypoints.txt
MOV_0009_frame51_keypoints.txt
MOV_0001_frame18_keypoints.txt
MOV_0017_frame18_keypoints.txt
MOV_0003_frame100_keypoints.txt
MOV_0018_frame50_keypoints.txt
MOV_0021_frame28_keypoints.txt
MOV_0013_frame72_keypoints.txt
MOV_0001_frame36_keypoints.txt
MOV_0003_frame56_keypoints.txt
MOV_0007_frame251_keypoints.txt
MOV_0007_frame301_keypoints.txt
MOV_0007_frame724_keypoints.txt
MOV_0007_frame674_keypoints.txt
MOV_0020_frame23_keypoints.txt
MOV_0007_frame495_keypoints.txt
MOV_0012_frame79_keypoints.txt
MOV_0021_frame4_keypoints.txt
MOV_0007_frame81_keypoints.txt
MOV_0016_frame13_keypoints.txt
MOV_0007_frame428_keypoints.txt
MOV_0007_frame578_keypoints.txt
MOV_0020_frame89_keypoints.txt
MOV_0007_frame246_keypoints.txt
MOV_0007_frame316_keypoints.txt
MOV_0003_frame41_keypoints.txt
MOV_0020_frame34_keypoints.txt
MOV_0007_frame733_keypoints.txt
MOV_0007_frame663_keypoints.txt
MOV_0007_frame482_keypoints.txt
MOV_0007_frame96_keypoints.txt
MOV_0018_frame47_keypoints

MOV_0003_frame105_keypoints.txt
MOV_0018_frame55_keypoints.txt
MOV_0013_frame77_keypoints.txt
MOV_0001_frame33_keypoints.txt
MOV_0003_frame209_keypoints.txt
MOV_0018_frame42_keypoints.txt
MOV_0013_frame60_keypoints.txt
MOV_0001_frame24_keypoints.txt
MOV_0021_frame87_keypoints.txt
MOV_0003_frame112_keypoints.txt
MOV_0001_frame99_keypoints.txt
MOV_0014_frame61_keypoints.txt
MOV_0007_frame313_keypoints.txt
MOV_0007_frame243_keypoints.txt
MOV_0003_frame44_keypoints.txt
MOV_0020_frame31_keypoints.txt
MOV_0019_frame49_keypoints.txt
MOV_0007_frame666_keypoints.txt
MOV_0007_frame736_keypoints.txt
MOV_0007_frame487_keypoints.txt
MOV_0007_frame93_keypoints.txt
MOV_0007_frame380_keypoints.txt
MOV_0007_frame544_keypoints.txt
MOV_0007_frame414_keypoints.txt
MOV_0007_frame161_keypoints.txt
MOV_0019_frame67_keypoints.txt
MOV_0007_frame648_keypoints.txt
MOV_0007_frame718_keypoints.txt
MOV_0019_frame1_keypoints.txt
MOV_0012_frame45_keypoints.txt
MOV_0021_frame14_keypoints.txt
MOV_0003_frame181_keypoint

MOV_0007_frame752_keypoints.txt
MOV_0007_frame602_keypoints.txt
MOV_0016_frame6_keypoints.txt
MOV_0013_frame2_keypoints.txt
MOV_0005_frame135_keypoints.txt
MOV_0016_frame65_keypoints.txt
MOV_0019_frame90_keypoints.txt
MOV_0003_frame9_keypoints.txt
MOV_0003_frame176_keypoints.txt
MOV_0001_frame40_keypoints.txt
MOV_0005_frame97_keypoints.txt
MOV_0018_frame26_keypoints.txt
MOV_0013_frame13_keypoints.txt
MOV_0001_frame57_keypoints.txt
MOV_0001_frame5_keypoints.txt
MOV_0005_frame80_keypoints.txt
MOV_0018_frame31_keypoints.txt
MOV_0021_frame49_keypoints.txt
MOV_0014_frame12_keypoints.txt
MOV_0017_frame79_keypoints.txt
MOV_0003_frame161_keypoints.txt
MOV_0007_frame449_keypoints.txt
MOV_0007_frame519_keypoints.txt
MOV_0016_frame72_keypoints.txt
MOV_0019_frame87_keypoints.txt
MOV_0005_frame122_keypoints.txt
MOV_0012_frame18_keypoints.txt
MOV_0007_frame181_keypoints.txt
MOV_0003_frame37_keypoints.txt
MOV_0007_frame230_keypoints.txt
MOV_0007_frame360_keypoints.txt
MOV_0007_frame745_keypoints.txt


MOV_0017_frame1_keypoints.txt
MOV_0016_frame31_keypoints.txt
MOV_0012_frame5_keypoints.txt
MOV_0012_frame66_keypoints.txt
MOV_0019_frame44_keypoints.txt
MOV_0003_frame49_keypoints.txt
MOV_0007_frame567_keypoints.txt
MOV_0007_frame437_keypoints.txt
MOV_0007_frame23_keypoints.txt
MOV_0007_frame142_keypoints.txt
MOV_0020_frame81_keypoints.txt
MOV_0001_frame101_keypoints.txt
MOV_0001_frame94_keypoints.txt
MOV_0005_frame43_keypoints.txt
MOV_0003_frame213_keypoints.txt
MOV_0009_frame60_keypoints.txt
MOV_0001_frame29_keypoints.txt
MOV_0021_frame37_keypoints.txt
MOV_0009_frame77_keypoints.txt
MOV_0003_frame204_keypoints.txt
MOV_0018_frame58_keypoints.txt
MOV_0021_frame20_keypoints.txt
MOV_0001_frame116_keypoints.txt
MOV_0001_frame83_keypoints.txt
MOV_0005_frame54_keypoints.txt
MOV_0003_frame108_keypoints.txt
MOV_0017_frame10_keypoints.txt
MOV_0007_frame570_keypoints.txt
MOV_0007_frame420_keypoints.txt
MOV_0007_frame34_keypoints.txt
MOV_0007_frame155_keypoints.txt
MOV_0007_frame89_keypoints.txt

MOV_0007_frame350_keypoints.txt
MOV_0007_frame200_keypoints.txt
MOV_0007_frame625_keypoints.txt
MOV_0020_frame72_keypoints.txt
MOV_0007_frame594_keypoints.txt
MOV_0012_frame28_keypoints.txt
MOV_0020_frame6_keypoints.txt
MOV_0007_frame698_keypoints.txt
MOV_0016_frame42_keypoints.txt
MOV_0005_frame112_keypoints.txt
MOV_0007_frame529_keypoints.txt
MOV_0007_frame479_keypoints.txt
MOV_0019_frame37_keypoints.txt
MOV_0007_frame748_keypoints.txt
MOV_0007_frame618_keypoints.txt
MOV_0018_frame2_keypoints.txt
MOV_0014_frame7_keypoints.txt
MOV_0012_frame15_keypoints.txt
MOV_0003_frame87_keypoints.txt
MOV_0007_frame280_keypoints.txt
MOV_0007_frame444_keypoints.txt
MOV_0007_frame514_keypoints.txt
MOV_0007_frame131_keypoints.txt
MOV_0007_frame50_keypoints.txt
MOV_0005_frame30_keypoints.txt
MOV_0018_frame81_keypoints.txt
MOV_0017_frame74_keypoints.txt
MOV_0021_frame44_keypoints.txt
MOV_0001_frame8_keypoints.txt
MOV_0003_frame260_keypoints.txt
MOV_0009_frame13_keypoints.txt
MOV_0021_frame53_keypoints.t

In [5]:
len(features)

2174

In [6]:
X=np.asarray(features)
X[0]

array([0.31741522, 0.32343403, 0.24497097, 0.18150937, 0.10601477,
       0.39902031, 0.46840039, 0.52884047, 0.32960449, 0.28124759,
       0.29327194, 0.29622772, 0.3807834 , 0.38985659, 0.39598727,
       0.29928845, 0.33251875, 0.27521494, 0.35362322, 0.41414864,
       0.42927236, 0.38681778, 0.26910444, 0.25397439, 0.3053949 ,
       0.29941127, 0.38989811, 0.38989465, 0.47139768, 0.41412269,
       0.38696482, 0.45943618, 0.38093967, 0.60135622, 0.6044008 ,
       0.79766236, 0.94553779, 0.59830588, 0.78854593, 0.93664047,
       0.28423393, 0.28413186, 0.29928441, 0.2962208 , 0.99993657,
       0.98785052, 0.9486458 , 1.        , 0.98794278, 0.95171344])

In [7]:
y=[]
for text_file in text_files:
    movie=text_file[0:8]
    if(movie=='MOV_0001'):
        y.append('narrow')
    if(movie=='MOV_0002'):
        y.append('narrow')
    if(movie=='MOV_0003'):
        y.append('narrow')
    if(movie=='MOV_0004'):
        y.append('normal')
    if(movie=='MOV_0005'):
        y.append('normal')
    if(movie=='MOV_0006'):
        y.append('wide')    
    if(movie=='MOV_0007'):
        y.append('normal')
    if(movie=='MOV_0008'):
        y.append('normal')
    if(movie=='MOV_0009'):
        y.append('normal')
    if(movie=='MOV_0010'):
        y.append('narrow')
    if(movie=='MOV_0011'):
        y.append('wide')
    if(movie=='MOV_0012'):
        y.append('wide')
    if(movie=='MOV_0013'):
        y.append('normal')
    if(movie=='MOV_0014'):
        y.append('normal')
    if(movie=='MOV_0015'):
        y.append('normal')
    if(movie=='MOV_0016'):
        y.append('wide')
    if(movie=='MOV_0017'):
        y.append('narrow')
    if(movie=='MOV_0018'):
        y.append('normal')
    if(movie=='MOV_0019'):
        y.append('wide')
    if(movie=='MOV_0020'):
        y.append('wide')    
    if(movie=='MOV_0021'):
        y.append('narrow')
        

In [8]:
len(y)

2174

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [11]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(max_depth=8) 
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=8)

In [12]:
text_files = [pos_text for pos_text in os.listdir('../text-file/test_set/') if pos_text.endswith('.txt')]

In [13]:
text_files

['MOV_0006_frame301_keypoints.txt',
 'MOV_0006_frame251_keypoints.txt',
 'MOV_0002_frame79_keypoints.txt',
 'MOV_0004_frame143_keypoints.txt',
 'MOV_0006_frame13_keypoints.txt',
 'MOV_0006_frame428_keypoints.txt',
 'MOV_0010_frame80_keypoints.txt',
 'MOV_0002_frame8_keypoints.txt',
 'MOV_0004_frame73_keypoints.txt',
 'MOV_0008_frame50_keypoints.txt',
 'MOV_0010_frame162_keypoints.txt',
 'MOV_0011_frame36_keypoints.txt',
 'MOV_0008_frame47_keypoints.txt',
 'MOV_0011_frame21_keypoints.txt',
 'MOV_0004_frame64_keypoints.txt',
 'MOV_0004_frame154_keypoints.txt',
 'MOV_0010_frame97_keypoints.txt',
 'MOV_0006_frame316_keypoints.txt',
 'MOV_0006_frame246_keypoints.txt',
 'MOV_0004_frame258_keypoints.txt',
 'MOV_0008_frame117_keypoints.txt',
 'MOV_0006_frame385_keypoints.txt',
 'MOV_0006_frame164_keypoints.txt',
 'MOV_0006_frame411_keypoints.txt',
 'MOV_0006_frame338_keypoints.txt',
 'MOV_0006_frame268_keypoints.txt',
 'MOV_0006_frame97_keypoints.txt',
 'MOV_0004_frame276_keypoints.txt',
 'MOV

In [14]:
features_test=[]
path='/Users/gwattal/squatsmart/text-file/test_set/'
for text_file in text_files:
    print(text_file)
    xi,yi,c=np.loadtxt(path + text_file).T
    features_test.append(np.hstack((xi,yi))/max(np.hstack((xi,yi))))

MOV_0006_frame301_keypoints.txt
MOV_0006_frame251_keypoints.txt
MOV_0002_frame79_keypoints.txt
MOV_0004_frame143_keypoints.txt
MOV_0006_frame13_keypoints.txt
MOV_0006_frame428_keypoints.txt
MOV_0010_frame80_keypoints.txt
MOV_0002_frame8_keypoints.txt
MOV_0004_frame73_keypoints.txt
MOV_0008_frame50_keypoints.txt
MOV_0010_frame162_keypoints.txt
MOV_0011_frame36_keypoints.txt
MOV_0008_frame47_keypoints.txt
MOV_0011_frame21_keypoints.txt
MOV_0004_frame64_keypoints.txt
MOV_0004_frame154_keypoints.txt
MOV_0010_frame97_keypoints.txt
MOV_0006_frame316_keypoints.txt
MOV_0006_frame246_keypoints.txt
MOV_0004_frame258_keypoints.txt
MOV_0008_frame117_keypoints.txt
MOV_0006_frame385_keypoints.txt
MOV_0006_frame164_keypoints.txt
MOV_0006_frame411_keypoints.txt
MOV_0006_frame338_keypoints.txt
MOV_0006_frame268_keypoints.txt
MOV_0006_frame97_keypoints.txt
MOV_0004_frame276_keypoints.txt
MOV_0002_frame40_keypoints.txt
MOV_0008_frame69_keypoints.txt
MOV_0015_frame65_keypoints.txt
MOV_0015_frame72_keypoin

MOV_0015_frame22_keypoints.txt
MOV_0006_frame292_keypoints.txt
MOV_0006_frame123_keypoints.txt
MOV_0004_frame180_keypoints.txt
MOV_0004_frame231_keypoints.txt
MOV_0010_frame43_keypoints.txt
MOV_0006_frame43_keypoints.txt
MOV_0004_frame113_keypoints.txt
MOV_0006_frame201_keypoints.txt
MOV_0006_frame351_keypoints.txt
MOV_0002_frame29_keypoints.txt
MOV_0010_frame132_keypoints.txt
MOV_0011_frame66_keypoints.txt
MOV_0004_frame23_keypoints.txt
MOV_0004_frame34_keypoints.txt
MOV_0008_frame17_keypoints.txt
MOV_0010_frame125_keypoints.txt
MOV_0011_frame71_keypoints.txt
MOV_0004_frame89_keypoints.txt
MOV_0008_frame6_keypoints.txt
MOV_0004_frame3_keypoints.txt
MOV_0006_frame216_keypoints.txt
MOV_0006_frame346_keypoints.txt
MOV_0004_frame208_keypoints.txt
MOV_0004_frame104_keypoints.txt
MOV_0006_frame54_keypoints.txt
MOV_0002_frame83_keypoints.txt
MOV_0004_frame184_keypoints.txt
MOV_0004_frame235_keypoints.txt
MOV_0010_frame47_keypoints.txt
MOV_0004_frame139_keypoints.txt
MOV_0006_frame69_keypoint

MOV_0006_frame360_keypoints.txt
MOV_0006_frame230_keypoints.txt
MOV_0011_frame57_keypoints.txt
MOV_0008_frame31_keypoints.txt
MOV_0015_frame80_keypoints.txt
MOV_0010_frame103_keypoints.txt
MOV_0004_frame12_keypoints.txt
MOV_0004_frame92_keypoints.txt
MOV_0006_frame101_keypoints.txt
MOV_0006_frame3_keypoints.txt
MOV_0002_frame25_keypoints.txt
MOV_0004_frame213_keypoints.txt
MOV_0010_frame61_keypoints.txt
MOV_0002_frame32_keypoints.txt
MOV_0004_frame204_keypoints.txt
MOV_0010_frame76_keypoints.txt
MOV_0006_frame116_keypoints.txt
MOV_0006_frame58_keypoints.txt
MOV_0004_frame108_keypoints.txt
MOV_0004_frame38_keypoints.txt
MOV_0015_frame17_keypoints.txt
MOV_0004_frame85_keypoints.txt
MOV_0010_frame129_keypoints.txt
MOV_0004_frame16_keypoints.txt
MOV_0015_frame39_keypoints.txt
MOV_0008_frame88_keypoints.txt
MOV_0011_frame53_keypoints.txt
MOV_0008_frame35_keypoints.txt
MOV_0010_frame107_keypoints.txt
MOV_0006_frame185_keypoints.txt
MOV_0010_frame58_keypoints.txt
MOV_0006_frame234_keypoints.t

In [15]:
X_test=np.asarray(features_test)
X_test[0]

array([0.43574922, 0.42334031, 0.33144306, 0.26394249, 0.21496772,
       0.50925035, 0.58601116, 0.62900171, 0.40513946, 0.34377293,
       0.27629846, 0.21187672, 0.47244396, 0.4970554 , 0.50007675,
       0.411219  , 0.45419455, 0.37749205, 0.47554335, 0.56751556,
       0.56763705, 0.48164697, 0.19346316, 0.17814857, 0.2149423 ,
       0.19962715, 0.26091837, 0.25793882, 0.37123893, 0.25488288,
       0.26096587, 0.37435222, 0.24869915, 0.57369136, 0.56761947,
       0.79135402, 0.95387804, 0.57678474, 0.78225277, 0.94163828,
       0.17803874, 0.17194087, 0.16895802, 0.15671084, 0.98768092,
       0.97543029, 0.95704171, 1.        , 0.99076333, 0.96307777])

In [16]:
X_test.shape

(1277, 50)

In [17]:
y_test=[]
for text_file in text_files:
    movie=text_file[0:8]
    if(movie=='MOV_0001'):
        y_test.append('narrow')
    if(movie=='MOV_0002'):
        y_test.append('narrow')
    if(movie=='MOV_0003'):
        y_test.append('narrow')
    if(movie=='MOV_0004'):
        y_test.append('normal')
    if(movie=='MOV_0005'):
        y_test.append('normal')
    if(movie=='MOV_0006'):
        y_test.append('wide')    
    if(movie=='MOV_0007'):
        y_test.append('normal')
    if(movie=='MOV_0008'):
        y_test.append('normal')
    if(movie=='MOV_0009'):
        y_test.append('normal')
    if(movie=='MOV_0010'):
        y_test.append('narrow')
    if(movie=='MOV_0011'):
        y_test.append('wide')
    if(movie=='MOV_0012'):
        y_test.append('wide')
    if(movie=='MOV_0013'):
        y_test.append('normal')
    if(movie=='MOV_0014'):
        y_test.append('normal')
    if(movie=='MOV_0015'):
        y_test.append('normal')
    if(movie=='MOV_0016'):
        y_test.append('wide')
    if(movie=='MOV_0017'):
        y_test.append('narrow')
    if(movie=='MOV_0018'):
        y_test.append('normal')
    if(movie=='MOV_0019'):
        y_test.append('wide')
    if(movie=='MOV_0020'):
        y_test.append('wide')    
    if(movie=='MOV_0021'):
        y_test.append('narrow')
        

In [18]:
len(y_test)

1277

In [19]:
tree_clf.score(X_test,y_test)

0.36021926389976505

In [41]:
with open('y_labels_train.txt', 'w') as f: #saving y labels to file
    for item in y:
        f.write("%s\n" % item)
with open('y_labels_test.txt', 'w') as f: #saving y labels to file
    for item in y_test:
        f.write("%s\n" % item)

In [42]:
np.savetxt("x_features_train.txt",X,delimiter=' ')
np.savetxt("x_features_test.txt",X_test,delimiter=' ')

In [21]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(multi_class='ovr')
model.fit(X, y)
# make predictions
yhat = model.predict(X_test)

In [24]:
model.score(X_test,y_test)

0.41895066562255284

In [51]:
model.score(X,y) # the difference in the two scores shows that the method is over fitting

0.906163753449862

In [57]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,model.predict(X_test))

array([[166,  97,   0],
       [132, 318,  32],
       [ 19, 462,  51]])

In [25]:
#42percent 

SyntaxError: invalid syntax (<ipython-input-25-f900bf6a0eb9>, line 1)

In [40]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=6, random_state=0)
clf.fit(X, y)
clf.score(X_test,y_test)

0.37196554424432265

In [50]:
clf.feature_importances_

array([0.02030303, 0.0102023 , 0.01243378, 0.03899531, 0.02626437,
       0.01775248, 0.00302794, 0.00784364, 0.00565672, 0.01270966,
       0.00542541, 0.04791281, 0.01693571, 0.00728177, 0.03073266,
       0.01949302, 0.03161001, 0.02350373, 0.01478941, 0.05112429,
       0.04318997, 0.04440654, 0.03761969, 0.0216888 , 0.04224869,
       0.03326273, 0.01908874, 0.01310566, 0.00408468, 0.03679771,
       0.01778856, 0.00066612, 0.05030364, 0.00318207, 0.00243761,
       0.02850936, 0.00958942, 0.00968545, 0.01829671, 0.001666  ,
       0.03756649, 0.04191185, 0.02843806, 0.01898109, 0.00053451,
       0.01651733, 0.00182393, 0.00468605, 0.00191616, 0.00600837])

In [55]:
clf.score(X,y)

1.0

In [52]:
len(y) +len(y_test)

3451

In [54]:
X.shape[0] + X_test.shape[0]

3451

In [59]:
print(y.count('narrow'))
print(y.count('normal'))
print(y.count('wide')) ##imbalanced dataset

599
1229
346


In [63]:
X.shape

(2174, 50)

In [73]:
xs = X.shape
x_new = np.zeros((xs[0], xs[1]+1))
x_new[:, :-1] = X
x_new[:,-1]=(X[:,14]-X[:,11])/(X[:,5]-X[:,2])

/Users/gwattal/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


/Users/gwattal/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [67]:
xs_test = X_test.shape
x_new_test = np.zeros((xs_test[0], xs_test[1]+1))
x_new_test[:, :-1] = X_test
x_new_test[:,-1]=max((X_test[:,14]-X_test[:,11])/(X_test[:,5]-X_test[:,2]),0.0)

/Users/gwattal/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [86]:
model = LogisticRegression(multi_class='ovr')
model.fit(x_new, y)
# make predictions
yhat = model.predict(x_new_test)
model.score(x_new_test,y_test)

/Users/gwattal/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/Users/gwattal/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/module

0.6844166014095536

In [87]:
confusion_matrix(y_test,model.predict(x_new_test))

array([[128, 135,   0],
       [123, 359,   0],
       [  0, 145, 387]])

In [89]:
model = LogisticRegression(multi_class='ovr')
model.fit(x_new, y)
# make predictions
yhat = model.predict(x_new_test)
model.score(x_new_test,y_test)

/Users/gwattal/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/Users/gwattal/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/module

0.6844166014095536

In [70]:
x_new[:,-1]

array([0.64758176, 0.68917335, 1.21455539, ..., 0.        , 1.62419154,
       0.88339066])

In [76]:
np.argwhere(np.isinf(x_new_test))

array([[370,  50],
       [713,  50]])

array([[ 679,   50],
       [1330,   50],
       [1565,   50],
       [2034,   50],
       [2151,   50]])

In [85]:
x_new[np.isinf(x_new)]=0.0
x_new_test[np.isinf(x_new_test)]=0.0

In [84]:
np.argwhere(np.isinf(x_new))

array([], shape=(0, 2), dtype=int64)

In [90]:
import pickle
# save the model to disk
filename = 'ovr_logistic_regression_model.sav'
pickle.dump(model, open(filename, 'wb'))
 
# some time later...
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(x_new_test, y_test)
print(result)

0.6844166014095536
